### ISSUE TITLE
Setup language does not work

### ISSUE THREAD

**Issue by Lvaskz** [matze/inkscape-flatpak#6]
The setup language does not work.
Hello, this package of inkscape does not allow me to modify the language of the interface to Spanish. Preferences: Language: Spanish, I change it and restart inkscape and interface. When you restart the interface it is still in English.

**Comment by matze** [comment]
Thanks for the report, I will investigate the issue but it might take a few days.

**Comment by matze** [comment]
Okay, the problem is with the bundle (which is not the preferred way to install Flatpaks anyway) which installs the locale data but cannot be found for a reason by Inkscape.

The quickest way for you would be to remove the flatpak (`flatpak uninstall org.inkscape.Inkscape`) and install it from flathub:

    $ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    $ flatpak install flathub org.inkscape.Inkscape

That way you also get semi-automatic updates.
