### ISSUE TITLE
Question: ready for 0.92.3?

### ISSUE THREAD

**Issue by Moini** [matze/inkscape-flatpak#7]
Hi there, 

I've been updating release info for pending 0.92.3 release.
Is the flatpak ready to add to the website?

Thank you!

**Comment by matze** [comment]
Where can I find the release tarball for 0.92.3? And by the way, I'd really encourage the Inkscape people to drop the bundled flatpak in favor of a link to the [flathub](https://flathub.org/) website. In terms of updates, using a flatpak repository is more convenient for users.

**Comment by Moini** [comment]
Hi @matze - seems you've been missed in the packager release announcement :-( Thanks for getting back to me.

From your reply, I'm not sure I get what we'd need to do:

- would you like to be included in the next packager release announcement? (tagging @bryceharrington - he keeps the list of people to contact for a release)
- or would someone else need to be included for flathub?
- would you like to provide a package for 0.92.3? Or would you rather not?

Can you help us out by providing the correct (best, ideal from your view) content for the releases app on our website? 

https://inkscape.org/en/releases/ (this is also where you can find the source tarball)

**Comment by Moini** [comment]
https://inkscape.org/en/release/0.92.3/ , to be more specific.

**Comment by carlo-strata** [comment]
I don't understand why Inkscape releases for linux include snap (may be too Canonical "related"...) package, but not (any more) flatpak (more free, imho, despite the RedHat original project...).

Application like Gimp, Octave, Audacity, Xournal, Krita ... are present and well updated in flatpak...

So I definitively don't understand if is a "political" reason or something else...

Finally, what exactly means @matze speaking about flathub link? Have we to go away from here (github.com)?

May I help to build a stable updating "system"? I am an experienced Italian computer engineer loving FLOSS at all.

Have all a nice evening,

Carlo

**Comment by matze** [comment]
> I don't understand why Inkscape releases for linux include snap (may be too Canonical "related"...) package, but not (any more) flatpak (more free, imho, despite the RedHat original project...).

It's because someone needs to provide them that. In the beginning (before Flathub) I was building repository-independent bundles which they were hosted on the Inkscape site. Since I upload the Flatpak instructions on [Flathub](https://github.com/flathub/org.inkscape.Inkscape), I kind of lost contact (and somehow missed this issue, sorry @Moini). Ideally, a link to the [Flathub entry for Inkscape](https://flathub.org/apps/details/org.inkscape.Inkscape) should suffice, I or others are usually pretty quick updating.

**Comment by bryceharrington** [comment]
On Tue, Sep 04, 2018 at 10:10:42AM -0700, carlo-strata wrote:
> I don't understand why Inkscape releases for linux include snap (may be too Canonical "related"...) package, but not (any more) flatpak (more free, imho, despite the RedHat original project...).
> 
> Application like Gimp, Octave, Audacity, Xournal, Krita ... are present and well updated in flatpak...
> 
> So I definitively don't understand if is a "political" reason or something else...
> 
> Finally, what exactly means @matze speaking about flathub link? Have we to go away from here (github.com)?
> 
> May I help to build a stable updating "system"? I am an experienced Italian computer engineer loving FLOSS at all.

Yes, certainly.  Like Matthias alluded to, the range of packaging
formats we support is limited only by the interests of people (like you)
willing to put in the hard work to craft the packages.

Technically, the only package format we absolutely guarantee is the
source tarball, however we do strive to ensure coverage of common
platforms.  But ultimately it depends entirely on the willingness of
volunteers with the time and know how to create them.

Of course, people's time and interest change, and so sometimes
responsibility for a given package format will have to be handed off to
a new maintainer.  If you'd be willing to take it on, just check in with
the prior maintainer, and then let me know and I'll add you to the
contact list for future releases.

Bryce

**Comment by Moini** [comment]
@matze Glad to see you! :-D 

How can I see which version is currently available on flathub? Would it be possible for you to add the missing info on that linked page (version, last updated, developer: Inkscape project) to the package format (or wherever it would need to be added?)

I'd like to be able to see which version is available, so I can add it to the correct part of the releases app on our website (on my own, for any future version, without needing to ask you ;-) ).

@bryceharrington I'm wondering if packaging for flatpak should somehow be mirrored/integrated in our repo? I think we're including snap packaging, deb packaging, Windows and macOS packaging in the project. Of course, this would also depend on what @matze wants.

**Comment by Moini** [comment]
@bryceharrington It looks to me as if @matze /were/ keeping things up-to-date. Having a couple more people who know how things work is always a very good idea, though. Maybe both would like to join Inkscape on gitlab as developers...? Just thinking out loud.

**Comment by bryceharrington** [comment]
On Tue, Sep 04, 2018 at 01:06:35PM -0700, Moini wrote:
> @matze Glad to see you! :-D 
> 
> How can I see which version is currently available on flathub? Would it be possible for you to add the missing info on that linked page (version, last updated, developer: Inkscape project) to the package format (or wherever it would need to be added?)
> 
> I'd like to be able to see which version is available, so I can add it to the correct part of the releases app on our website (on my own, for any future version, without needing to ask you ;-) ).
> 
> @bryceharrington I'm wondering if packaging for flatpak should somehow be mirrored/integrated in our repo? I think we're including snap packaging, deb packaging, Windows and macOS packaging in the project. Of course, this would also depend on what @matze wants.
> 

If it can be stored in a subdir under the packaging/ directory then
there'd be no issue including it, if that'd help the packaging work.

We've been striving to minimize the amount of stuff in the root
directory, so if flatpak needs nothing in root that'd be ideal.  If it
does need a file or two, we've made allowances for other stuff before,
so it'd certainly be discussable.

I've also been striving to minimize the number of manual steps for the
source tarball distribution generation process.  If there is metadata
like version numbers that have to be set in flatpak's config files as
part of the dist process, I would just request it be implemented to be
done automatically in the cmake scripts.  Flatpak may not need anything
like this, but if it does there are examples from what other packaging
systems have done that can be used as reference.

Bryce

**Comment by matze** [comment]
> How can I see which version is currently available on flathub? Would it be possible for you to add the missing info on that linked page (version, last updated, developer: Inkscape project) to the package format (or wherever it would need to be added?)

This actually depends on you ;-) I was once cooking up a small patch but since forgot about it. Essentially you need to provide release information in your appdata metadata file as documented [here](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases) and it will be pulled out automatically.

> Of course, this would also depend on what @matze wants.

Ideally, I would not want you to do anything besides linking to that Flathub entry page ;-) The Flathub repo is not a source repository but a binary repository (unlike the bundles I gave you before, it also offers both 32-bit and 64-bit x86 and ARM architectures) from which users can install Inkscape either via command line (`flatpak install flathub org.inkscape.Inkscape`) or via a graphical user interface (e.g. GNOME Software). If you want to pull in the build description that is located [here](https://github.com/flathub/org.inkscape.Inkscape) that means you either want to set up your own Flatpak repository (why duplicate work?) or offer Flatpak bundles (these are standalone but do not allow for upgrades). At the end, it's up to you :-)

**Comment by Moini** [comment]
> Essentially you need to provide release information in your appdata metadata file as documented here and it will be pulled out automatically.

Like this: https://gitlab.com/inkscape/inkscape/blob/master/inkscape.appdata.xml.in ? So we'd need to backport that to 0.92.x and that's all?

Okay, so it doesn't make any sense to have the build description json file included in the project. While that's fine with me, I'd like to understand... if you have the time for it.

I'd have thought it works like this: 
you register at flathub, tell them where to find the json file, and then they build the package for you - in that case, why would it matter where the file lives? Does it need to be the only file in the repository?

**Comment by matze** [comment]
> Like this: https://gitlab.com/inkscape/inkscape/blob/master/inkscape.appdata.xml.in ? So we'd need to backport that to 0.92.x and that's all?

Yes, exactly like this (and by the way that's also the reason why they could offer those buttons for website, donation, help and issues).

> why would it matter where the file lives?

Because they control where the file lives and their build bots are integrated with GitHub I suppose. There is actually no real registration involved, for a new project you open a pull request on their main [GitHub](https://github.com/flathub) project and once approved they will create a new repository for the Flatpak build description and auxiliary files, e.g. https://github.com/flathub/org.inkscape.Inkscape in your case. From there on it's all automatic. For example, yesterday I upgraded the ghostscript dependency from 9.23 to 9.24 which triggered a rebuild even though no new Inkscape version was released. For the user it feels a bit like a distribution-agnostic package manager.

One good thing about this separation into separate repositories is, that we can have package-related issues on GitHub which would just be noise if they were reported on your GitLab instance.

**Comment by Moini** [comment]
Thank you very much, @matze ! I understand now. Thanks for hinting to the other options as well (donations and help link can't hurt)!

I could probably do the backporting (and find out about the other options) during the hackfest.

I guess we won't be able to test if it works until the next version is released (as we don't modify the released 0.92.3 branch)?

**Comment by Moini** [comment]
Added flatpak to releases app on website, and found the (optimizable) button links in the appdata file :)

**Comment by matze** [comment]
> I guess we won't be able to test if it works until the next version is released (as we don't modify the released 0.92.3 branch)?

There is the possibility to patch anything in the sources before building the Flatpak. So, in theory I could patch the appdata file and remove that patch when a new release is out. If you think this is a good idea, I could start earliest tomorrow evening.

**Comment by Moini** [comment]
Thank you for offering this, @matze ! This is very nice of you.

I had hoped that maybe they provide a test instance, so we could see if it works before the next release, and be able to fix before that. 

Patching would be an even better option, though. It's not urgent, but yes, it would be cool! I'll only get to fix up the file on Monday earliest (I don't expect much real work can be done on the first day of the hackfest - but who knows...). When I have fixed up the file for 0.92.3 (and I'll probably go over the one for 1.0, too), I'll contact you via this report here.

**Comment by matze** [comment]
> Patching would be an even better option, though. It's not urgent, but yes, it would be cool! 

I had a few minutes before I had to leave, and apparently patching is a viable solution for now: https://flathub.org/apps/details/org.inkscape.Inkscape

**Comment by matze** [comment]
By the way, I will close this issue now and by the end of the work disable this repository. Further communication should then best happen at the Flathub repo.

**Comment by Moini** [comment]
Thank you for letting me know, @matze !

**Comment by Moini** [comment]
Made a couple of merge requests for master and 0.92.x branch, so the patch might not be needed anymore for 0.92.4:
https://gitlab.com/inkscape/inkscape/merge_requests/345
https://gitlab.com/inkscape/inkscape/merge_requests/346

**Comment by matze** [comment]
Thanks for the update! By the way, I just logged in with my GitHub account, so next time there is some minor change required from my side, I could also open a PR myself.
